### PR TITLE
added the option for the styles to be loaded in node

### PR DESCRIPTION
**Pull request by alejandromaka**
in order to make Tooltip work for an isomorphic app, we need to be able to load local styles in node (aka. not require window or document, which is what style-loader does).
there's this package https://github.com/kriasoft/isomorphic-style-loader that does pretty much the same as regular style-loader, with the exception of having to wrap the view in a parent view setting context for children, and that "withStyles" wrapper view.
this works for both client and server.

what do you guys think of adding this? we're trying to move bomt to isomorphic and this will make the Tooltip usable inside it.

### CODE REVIEW

**Comment by nitruxa** [comment]
@alejandromaka have you checked this one? https://github.com/halt-hammerzeit/universal-webpack

**Comment by kostasmanionis** [comment]
screen shot 2016-08-03 at 14 39 14
How does this change the size of the tooltip?

I was thinking about using `css-loader/locals` to only export the class names & extract the css to a separate file using `extract-text-webpack-plugin`. But then how would we get the css file on to the page? This wouldn't work, right?

Do we have any alternatives here?

**Comment by alejandromaka** [comment]
@nitruxa i havent seen it. ill check it out.
@kostasmanionis i think we could do that, and i've seen that solution in some blogs (like use "whatever-local-class" instead of styles.localClass). but the only thing is that we would have to add a wrapper component that would do the `require('./styles.css')` inside `componentDidMount`. which im not opposed to doing either. but i think it's possible that the classnames might conflict with other ones unless we make them very unique.

**Comment by alejandromaka** [comment]
oh is that what you meant @kostasmanionis ?

**Comment by kostasmanionis** [comment]
I was thinking about doing the same thing we do for `1stdibs.com`. Extracting just the class names 
```
module.exports = {
    "defaultStyle": "Tooltip__defaultStyle___2PHGC",
    "defaultClose": "Tooltip__defaultClose___3C4eQ",
    "defaultTriangle": "Tooltip__defaultTriangle___2yE9C",
    "container": "Tooltip__container___1iGSw",
    "inner": "Tooltip__inner___34nOg",
    "svg": "Tooltip__svg___1D5qj",
    "close": "Tooltip__close___39mNB Tooltip__svg___1D5qj",
    "triangle": "Tooltip__triangle___XBkZH Tooltip__svg___1D5qj",
    "triangleStroke": "Tooltip__triangleStroke___1qO6p",
    "top": "Tooltip__top___3PYiq",
    "left": "Tooltip__left___2ocL0",
    "right": "Tooltip__right___1Jius"
};
```

And moving the css to separate file. But I can't think of an easy way to get extracted style file on the webpage. So it's probably not a really good way to do things... 😄

The only issue I have with this is the size. It doubles it, from 7370 bytes (minified&gzipped) to 15714 :(

**Comment by gedas-monginas** [comment]
yeah, don't like bloating out this file just for styles, would the simple solution of using Smacss style global classes just do the trick? And then each project would style however they want :)

**Comment by alejandromaka** [comment]
@gedas-monginas like the example i gave above?

**Comment by gedas-monginas** [comment]
@alejandromaka sorry forgot to respond to this some how, the answer: yeah :)

**Comment by twhid** [comment]
bump... we need a fix for this. Are there concrete alternatives to what @alejandromaka has proposed?

**Pull request closed without merging**
