### PR TITLE
chore: MG-1517 added datatn functionality

### PR DESCRIPTION
**Pull request by mecciau**

### CODE REVIEW

**Comment by moriko** [comment]
OMG is this one even used anywhere? This is deprecated...

**Comment by mecciau** [comment]
https://github.com/1stdibs/1stdibs.com/blob/master/dibs/assets/js/dealerDirectory/components/DealerTile/DealerTile.jsx#L5

**Comment by moriko** [comment]
Think that the better solution would be to create ticket for the MCPERSON tema to replace the old one with the new Tooltip form dibs-elements that has the `dataTn`: https://github.com/1stdibs/dibs-components/blob/master/packages/dibs-elements/src/Tooltip/index.jsx#L31

**Comment by Tyriont** [comment]
@moriko I'm not sure it's all THAT deprecated...

https://github.com/search?p=1&q=org%3A1stdibs+dibs-react-tooltip&type=Code

Quite a lot of usage still dotted around the place.  Definitely agree we should replace these usages but that's a much bigger effort, so would be nice to get this merged for now and then work on that after.

**Comment by moriko** [comment]
Then suggest adding `isRequired` for the `dataTn` :)
And later I will just add console warning that this package is deprecated :)

**Comment by moriko** [comment]
@mecciau for the `isRequired` it's up to you to decide if you want to add it or not :))
Just wanted more warning for developer so maybe would notice that this oldy it there :D

**Comment by moriko** [comment]
`0.6.4`

**Pull request merged**
